
spring:
  application:
    name: ranking
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8080}

  datasource:
    url: jdbc:postgresql://localhost:5432/katadb?currentSchema=evaluations
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate:
    #  ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      group-id: ranking-ms
      bootstrap-servers: localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.juandavyc.ranking.domain.model.kafka"
        spring.json.use.type.headers: false


server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE:http://localhost:8070/eureka/}"